### ISSUE TITLE
BE- Create user-app

### ISSUE THREAD

**Issue by ALewandowska-sys** [ALewandowska-sys/chatApp#18]
Create new package userApp with:
- entity (UserApp)
- repo
- DTO (UserAppDto)
- mapper
- service (basic CRUD operation)
- controller

Remember that we recognize 3 models of naming parameters:
1. for class names we use Upper Camel Case (UserApp)
2. for parameters in Java we use Lower Camel Case (createdAt)
3. for column in database we use Snake Case (created_at)
that is why, when you create UserApp entity, you have to add annotation ` @Column(name = "created_at") ` for `createdAt` field

This field is more complicated, because we want to initilize it automatically (always when user is create). You have to use:
- ` @CreationTimestamp ` annotation for this field
- don' t add this parameter to constructor
- in liquibase file we use ` defaultValue="NOW()" `

This photo show you how this entity looks in database (type `date` was changed to `timestamp`). You can use `01_18_create_user_table.xml` file for inspiration (you only have to add a created_at column).
![image](https://user-images.githubusercontent.com/82601472/220704618-fcc615e4-88d7-4044-8bf0-ee1845fd477c.png)

**Comment by mrsebo24** [comment]
I'll try :D
